name: 'Deploy Jitsi Component'
description: 'Build and deploy a jitsi component'
inputs:
  component:
    description: 'One of the following values: jibri, jicofo, jigasi, jvb, prosody, web'
    required: true
  docker-username:
    description: 'Docker Hub username'
    required: true
  docker-password:
    description: 'Docker Hub password'
    required: true
  tag:
    description: 'Docker image tag'
    required: true
    default: 'latest'
  kube-config:
    description: 'Kube config yaml file'
    required: true
  kube-config-file:
    description: 'Where to put kubeconfig file'
    required: true
    default: '$HOME/.kubeconfig'

runs:
  using: 'composite'
  steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ inputs.docker-username }}
        password: ${{ inputs.docker-password }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v5
      env:
        DOCKER_BUILDKIT: '1'

      with:
        context: ./${{ inputs.component }}
        push: true
        tags: ${{ inputs.docker-username }}/${{ inputs.component }}:${{ inputs.tag }}
        cache-from: type=registry,ref=${{ inputs.docker-username }}/${{ inputs.component }}:buildcache
        cache-to: type=registry,ref=${{ inputs.docker-username }}/${{ inputs.component }}:buildcache,mode=max
        builder: ${{ steps.setup-buildx.outputs.name }}

    - name: Setup kubeconfig
      shell: bash
      run: |
        echo "${{ inputs.kube-config }}" > "${{ inputs.kube-config-file }}"
        chmod 600 "${{ inputs.kube-config-file }}"

    - name: Deploy to Kubernetes
      shell: bash
      run: |
        export KUBECONFIG="${{ inputs.kube-config-file }}"
        POD_NAMES=$(kubectl get pods --no-headers=true | grep ${{ inputs.component }} | awk '{print $1}')
        if [ -n "$POD_NAMES" ]; then
          echo "$POD_NAMES" | xargs -P 16 -n 1 kubectl delete pod
        else
          echo "No matching pods to delete."
        fi
